### PR TITLE
Example card title div

### PR DESCRIPTION
**Pull request by dnevarez**
Both components for the option buttons are complete and mount and unmount from page.

### CODE REVIEW

**Comment by asBrettisay** [comment]
@dnevarez In my browser the modal is cut off by the edge of the screen.

screen shot 2016-07-21 at 3 46 46 pm

See how it is cut off on the edge? What's the deal there?

**Comment by dnevarez** [comment]
I had a problem with that yesterday. I was able to fix that this morning so the components render on the screen and not off them. It's in my last commit, so that fix will be included in my next push.

**Comment by asBrettisay** [comment]
@dnevarez if you can add it to this branch, I can include it in this pull request.

**Comment by dnevarez** [comment]
I've added the fix to this branch, along with another commit. It should wrap this branch, unless you notice something else that's broken.

**Pull request merged**
